### ISSUE TITLE
dataset config error when training on CARLA dataset

### ISSUE THREAD

**Issue by noahcao** [nrhine1/precog#7]
I tried to train esp with carla town01 dataset downloaded from the link you provided.

As all .json files in the provided dataset are named "ma_datum_*.json", so I modified in *conf/dataset/carla_town01_A1_T20_v2.yaml*:

> match_prefix: "ma_datum_*"

because training still fails with some other errors:

> Traceback (most recent call last):
  File "/home/jinkun/git/precog/precog/esp_train.py", line 124, in <module>
    if __name__ == '__main__': main()
  File "/home/jinkun/anaconda3/envs/precog/lib/python3.6/site-packages/hydra/main.py", line 25, in decorated_main
    strict,
  File "/home/jinkun/anaconda3/envs/precog/lib/python3.6/site-packages/hydra/_internal/utils.py", line 48, in run_hydra
    hydra.run(overrides=args.overrides)
  File "/home/jinkun/anaconda3/envs/precog/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 111, in run
    job_subdir_key=None,
  File "/home/jinkun/anaconda3/envs/precog/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 91, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/jinkun/git/precog/precog/esp_train.py", line 23, in main
    def main(cfg): optimize(prepare_for_optimization(cfg))
  File "/home/jinkun/git/precog/precog/esp_train.py", line 27, in optimize
    with tf.contrib.summary.always_record_summaries(): opt.optimize()
  File "/home/jinkun/git/precog/precog/optimizer/sgd_optimizer.py", line 75, in optimize
    self._static_create_singleton()
  File "/home/jinkun/git/precog/precog/optimizer/sgd_optimizer.py", line 148, in _static_create_singleton
    input_ = self.dataset.get_minibatch(split='train', mb_idx=0, is_training=True)
  File "/home/jinkun/git/precog/precog/utils/log_util.py", line 48, in log_wrapper
    ret = wrapped_func(*args, **kwargs)
  File "/home/jinkun/git/precog/precog/dataset/serialized_dataset.py", line 109, in get_minibatch
    k = lambda _, _k: getattr(_, self.keyremap[_k])
  File "/home/jinkun/git/precog/precog/dataset/serialized_dataset.py", line 114, in <listcomp>
    player_experts = np.stack([np.asarray(k(_, 'player_future')) for _ in data], 0)[None]
  File "/home/jinkun/git/precog/precog/dataset/serialized_dataset.py", line 109, in <lambda>
    k = lambda _, _k: getattr(_, self.keyremap[_k])
  File "/home/jinkun/anaconda3/envs/precog/lib/python3.6/site-packages/attrdict/mixins.py", line 82, in __getattr__
    cls=self.__class__.__name__, name=key
AttributeError: 'AttrDict' instance has no attribute 'S_future_world_frame'

Could you help to write some guidelines about how to train a model with the provided CARLA dataset? Thanks!

**Comment by yangyichun1997** [comment]
@noahcao I also have the same problems too ! Would you mind to ask how to solve this issue afterward?

**Comment by noahcao** [comment]
@yangyichun1997 I still haven't fixed that. Waiting for some solution provided by the author or someone else.

**Comment by XindiWu** [comment]
I also had the same problem (format mismatch) if you are also using the data provided from [precog_carla_dataset](https://github.com/nrhine1/precog_carla_dataset) here's an easy way to solve it - (thanks to @nrhine1 and my teammate @SwapnilPande for the help): 
Let's say we want to use the carla_town01_A1_T20_v1.yaml config file, and we need to change the following parts:
match_prefix: "feed_*"                              ->     match_prefix: "ma_*"
player_future: 'S_future_world_frame'     ->     player_future: 'player_future'
player_past: 'S_past_world_frame'          ->     player_past: 'player_past'
player_yaw: 'yaws'                                      ->      player_yaw: 'player_transform'

In the interface.py, we can add another function correct_yaws at the very beginning to map from the 4x4 player transform tensors to a scalar yaw (we can add it here: [line23](https://github.com/nrhine1/precog/blob/master/precog/interface.py#L23)
```
def correct_yaws(yaws):
    if yaws.shape == (10, 1, 4, 4):
        if type(yaws) == 'tensorflow.python.framework.ops.Tensor':
            yaws = tf.math.atan2(yaws[:,:,1,0], yaws[:,:,0,0])
        else:
            yaws = np.arctan2(yaws[:,:,1,0], yaws[:,:,0,0])
    return yaws
```

and call this function at these three place: 
1. [line 509](https://github.com/nrhine1/precog/blob/master/precog/interface.py#L509)
`yaws = correct_yaws(yaws)`

2. [in between line585+586](https://github.com/nrhine1/precog/blob/master/precog/interface.py#L585)
`yaws = correct_yaws(yaws)`

3. [in between line693+694](https://github.com/nrhine1/precog/blob/master/precog/interface.py#L693)
`yaws = correct_yaws(yaws)`

In the serialized_dataset.py, we use this function correct_yaws again, and call it at [line142](https://github.com/nrhine1/precog/blob/master/precog/dataset/serialized_dataset.py#L142) outside of the if-else.

Also, for plotting, in plot.py you can change the definitions of grey_pixels and red_pixels to be where the lidar > 0.9 for visualization purposes.

**Comment by noahcao** [comment]
@XindiWu Thanks Xindi! Will try that solution.
